### ISSUE TITLE
chore: Improve git & npm workflow

### ISSUE THREAD

**Issue by philippefutureboy** [arthurintelligence/node-fs-filesystem#10]
Improve git workflow:

- Add commitizen + conventional changelog

Improve npm workflow:

- Remove yarn.lock, move to npm
- Add watch script
- Add dev script
- Add esm export
- Remove mockery devDependency

**Comment by philippefutureboy** [comment]
* Added Greenkeeper to the repository – Still not sure if enabled
* Updated AppVeyor CI – It was not working – Need to wait for some PR action to confirm if active

**Comment by philippefutureboy** [comment]
Note: Will have to update travis & appveyor configurations not to use `yarn` anymore

**Comment by philippefutureboy** [comment]
^ Moved that to greenkeeper/initial

**Comment by jacargentina** [comment]
I 've finished the code for the tests to work again. Great! 🎉
