### ISSUE TITLE
Linux: test fails when LANG is not english; parsing is weak on a new test case

### ISSUE THREAD

**Issue by jacargentina** [arthurintelligence/node-fs-filesystem#15]
I've found that parsing currently depends on specific english strings; i'm from Argentina (spanish).

For example, `npm run test` with `LANG=es_AR.utf8` makes test fail like this:

```
1) node-fs-filesystem
       linux integration tests
         native tests
           should properly parse the output of the filesystem command:
     TypeError: Cannot read property 'slice' of null
```

`null` is a failing `match` for the string `/Disk\s(.*):\s.*,\s(\d+)\sbytes,\s(\d+) sectors/` on src/linux/linux.js:116

On spanish **Disk** is **Disco**

**Comment by philippefutureboy** [comment]
Great! So we should have a disclaimer on the README page that the library is locale/language dependent. 

We can manually extend the i18n coverage with something like the following:

1. Add a i18n dictionary to the library for each key for each distro affected (linux and beyond)
2. Replace the static regexes with `new RegExp(...)` with the keys dynamically fetched from the i18n dictionary

Let me know what you think,

Have a wonderful day ✨

**Comment by jacargentina** [comment]
@philippefutureboy I was thinking of another easier solution: we can force the environment for the child_process to have the LANG we need, ie `LANG=en_US.utf8`...  using [options.env](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback), right?

**Comment by philippefutureboy** [comment]
Wonderful! Let me know how it goes for the MacOS side of things

**Comment by jacargentina** [comment]
I'm now trying to make parsing even better; if the user has no enough permissions, fdisk show errors, and then parsing is affected with strange errors like calling `slice` on an empty matches array.

**Comment by jacargentina** [comment]
Fix/4 is now included here.
