### ISSUE TITLE
Windows: Non-native testing of Linux Integration Test Fails

### ISSUE THREAD

**Issue by philippefutureboy** [arthurintelligence/node-fs-filesystem#2]
Non-priority since does not affect usability of the software, nor is present in AppVeyor's tests, but optimally should be resolved for future contributors that use Windows platform.

Testing on a W7 Pro 64bit VM results in the following error:

![virtualbox_ node js w7 pro x86_64 clean_11_11_2017_09_06_02](https://user-images.githubusercontent.com/31741972/32694781-1d10f79a-c717-11e7-8271-c635513cbf51.png)

**Comment by jacargentina** [comment]
This is now solved on #15 🎉
