### ISSUE TITLE
AppVeyor CI: Non-Native Linux Integration Test Fails `volume.description` should be a string

### ISSUE THREAD

**Issue by philippefutureboy** [arthurintelligence/node-fs-filesystem#3]
Non-priority since does not affect functionality.

Non-native integration test for Linux fails to add a volume.description from the static input for volume `sdc` (`/test/src/linux/input.txt`, line 45). For some reason the same code does not produce an error on Linux when tested.

**Comment by jacargentina** [comment]
Solved on #15 🎉
