### ISSUE TITLE
Windows: removable is always null

### ISSUE THREAD

**Issue by pdirksen** [arthurintelligence/node-fs-filesystem#5]
`wmic logicaldisk get caption,description,..,drivetype`

_DriveType_ is returned as an integer corresponding to the type of disk drive the logical disk represents:

0 = Unknown
1 = No Root Directory
2 = Removable Disk
3 = Local Disk
4 = Network Drive
5 = Compact Disc
6 = RAM Disk

**Comment by jacargentina** [comment]
@pdirksen Looking at this, and my new issue #12, there is the "description" field which shows the "correct drive type" ?

**Comment by jacargentina** [comment]
@pdirksen so you basically need `removable: (disk.DriveType == 2)` ?

**Comment by pdirksen** [comment]
@jacargentina This and extending the constant `COMMAND` to get the drivetype as well.

**Comment by pdirksen** [comment]
Unfortunately the wmic columns in the output is always sorted, regardless of the order that has been set.

Before:
`Caption  Description  DeviceID  FileSystem  FreeSpace  Name  Size  VolumeName `
After:
`Caption  Description  DeviceID  DriveType  FileSystem  FreeSpace  Name  Size  VolumeName `

**Comment by jacargentina** [comment]
@pdirksen thanks for that; now fixed.

@philippefutureboy adding an "empty CD-ROM" output example for windows, shows the parser is very weak; tests failing on the new input.txt; want to look at it? I think the main cause is there are many spaces (not just 2, and not tabs either) separating some fields on the last line for the empty CD-ROM I've added

**Comment by philippefutureboy** [comment]
Yes, definitely, I remember struggling on the spacing – I didn't know that `wmic` had a /format flag. The csv idea is definitely a great one!
