### ISSUE TITLE
filesystem.sync seems to be undefined

### ISSUE THREAD

**Issue by luoj027** [arthurintelligence/node-fs-filesystem#6]
I use this module just as you said in README.md.
filesystem function works fine.  But filesystem.sync turns to be undefined.

Look forward to your reply
Thank you !

**Comment by philippefutureboy** [comment]
Hi @luoj027!

Thanks for your interest in node-fs-filesystem!

We are currently looking it up in PR #7, should be merged within two days or so.

Have a wonderful day 🚀

Cheers,

Philippe
